name: Release

on:
  workflow_dispatch:
    inputs:
      version_scale:
        description: Version scale
        required: true
        type: choice
        default: "patch"
        options:
          - "minor"
          - "major"
          - "patch"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: Configure Git User
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
