name: Release

on:
  workflow_dispatch:
    inputs:
      version_scale:
        description: Version scale
        required: true
        type: choice
        default: "patch"
        options:
          - "minor"
          - "major"
          - "patch"

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: Configure Git User
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      - name: Bump version
        run: |
          ./scripts/bump_version.sh
      - name: Create a GitHub release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          script: |
            try {
              const response = await github.rest.repos.createRelease({
                draft: false,
                generate_release_notes: true,
                name: `v${{ env.RELEASE_VERSION }}`,
                owner: context.repo.owner,
                prerelease: false,
                repo: context.repo.repo,
                tag_name: `v${{ env.RELEASE_VERSION }}`
              });
            } catch (error) {
              core.setFailed(error.message);
            }
